name: Github action demo
on: [
  workflow_dispatch
  ]
jobs: 
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
        
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with: 
          resourceGroup: 'dotnetgilde'
          loadTestResource: 'dotnetgilde_loadtest'
          loadTestConfigFIle: './loadtest.yaml'
